
export const CFN_OUTPUT_SUFFIX_RESTAPI_DOMAINNAME = 'RestApiDomainName';
export const CFN_OUTPUT_SUFFIX_RESTAPI_URL = 'RestApiUrl';

export const CFN_OUTPUT_SUFFIX_GRAPHQL_DOMAINNAME = 'GraphQlDomainName';

export const CFN_OUTPUT_SUFFIX_DATASTORE_TABLENAME = 'TableName';

export const CFN_OUTPUT_SUFFIX_ASSETCDN_BUCKETNAME = 'AssetCdnBucketName';
export const CFN_OUTPUT_SUFFIX_ASSETCDN_DOMAINNAME = 'AssetCdnDomainName';
export const CFN_OUTPUT_SUFFIX_ASSETCDN_URL = 'AssetCdnUrl';

export const CFN_OUTPUT_SUFFIX_AUTH_USERPOOLID = 'UserPoolId';
export const CFN_OUTPUT_SUFFIX_AUTH_USERPOOL_CLIENTID = 'UserPoolClientId';
export const CFN_OUTPUT_SUFFIX_AUTH_IDENTITYPOOL_ID = 'IdentityPoolId';
export const CFN_OUTPUT_SUFFIX_AUTH_IDENTITYPOOL_AUTH_ROLEARN = 'IdentityPoolAuthRoleArn';
export const CFN_OUTPUT_SUFFIX_AUTH_IDENTITYPOOL_UNAUTH_ROLEARN = 'IdentityPoolUnAuthRoleArn';